import type { Prisma, PrismaClient, ReminderFormat, ScheduleRuleKind } from "@prisma/client";

/** Default reminder template slot definitions seeded when a project is created. */
export interface ReminderTemplateSlotDefinition {
  slotKey: string;
  name: string;
  reminderFormat: ReminderFormat;
  bodyTemplate: string | null;
  scheduleRuleKind: ScheduleRuleKind;
  dayOffset: number | null;
  clockTimeMyt: string | null;
  startOffsetMinutes: number | null;
  sortOrder: number;
}

/**
 * Authoritative Show Up caption copy from Dr Jasmine Community Show Up SOP
 * (nm-sop.vercel.app / vault PDF screenshots 2026-07-06).
 * Placeholders: {{workshopDay}} {{workshopDate}} {{workshopTime}} {{zoomLink}}
 * {{sessionDate}} {{sessionTime}} {{zoomId}} {{zoomPasscode}}
 */
export const REMINDER_TEMPLATE_SLOT_DEFINITIONS: readonly ReminderTemplateSlotDefinition[] = [
  {
    slotKey: "welcome",
    name: "Welcome",
    reminderFormat: "IMAGE",
    bodyTemplate: [
      "Hey everyone! 👋 Welcome to the official group for Dr. Jasmine's Reversing Diabetes Workshop 🤩",
      "",
      "You're in and this isn't just another group.",
      "",
      "Before the upcoming workshop, we'll be dropping:",
      "✅ Important workshop updates",
      "✅ Bonus health and recovery insights",
      "✅ Zoom links before the session",
      "",
      "The real transformation starts during the workshop.",
      "But what happens before that matters too.",
      "",
      "So stay close and keep an eye on this group.",
      "This could be the beginning of a very different health journey for you. 💚",
      "",
      "If you're ready to learn, reset, and take back control,",
      "🔥 Drop a quick reaction below to show you're READY!",
      "",
      "Let's do this!",
    ].join("\n"),
    scheduleRuleKind: "WEBINAR_DATE_OFFSET",
    dayOffset: -4,
    clockTimeMyt: "15:00",
    startOffsetMinutes: null,
    sortOrder: 1,
  },
  {
    slotKey: "countdown_2d",
    name: "2-Day Countdown",
    reminderFormat: "IMAGE",
    bodyTemplate: [
      "We're just 2 days away. ⏰",
      "",
      "Quick question before we begin...",
      "",
      "Have you noticed how sometimes your blood sugar level looks a bit better...",
      "but other times, no matter how careful you are, it still goes up and down?",
      "",
      "You try to eat better.",
      "You try to be more disciplined.",
      "You try to follow the advice you've been given.",
      "",
      "But the readings still fluctuate.",
      "The energy still drops.",
      "And deep down, there's still that worry about where this is heading.",
      "",
      "Most people assume diabetes is something you just have to manage forever.",
      "",
      "Control the blood sugar.",
      "Take the medication.",
      "Increase insulin if needed.",
      "And hope complications don't come later.",
      "",
      "But what if that's not the full picture? 🧐",
      "",
      "What if the real issue is that most people were only taught how to manage the numbers...",
      "but never shown how to understand what may actually be driving the condition underneath?",
      "",
      "And if you've ever felt frustrated because you've been trying...",
      "yet your diabetes still doesn't feel truly under control,",
      "this workshop will hit very differently for you.",
      "",
      "Because this isn't just about temporary blood sugar control.",
      "It's about understanding:",
      "",
      "✅ What may actually be keeping your blood sugar level unstable",
      "✅ Why some people end up needing more medication or insulin over time",
      "✅ What may need to be addressed if you want to reduce the risk of long-term complications",
      "",
      "When the right root causes are addressed,",
      "the body can finally start responding differently.",
      "And when they're not,",
      "even a lot of effort can still leave you stuck in the same cycle.",
      "",
      "Upcoming {{workshopDay}} - {{workshopDate}} @ {{workshopTime}}, Dr. Jasmine will break this down step by step.",
      "",
      "Once you start seeing diabetes from a different perspective,",
      "you stop guessing, stop going in circles,",
      "and start understanding what your body may actually need.",
      "",
      "Make sure you're there when it starts.",
      "This could be the session that changes how you look at diabetes completely 🔥",
    ].join("\n"),
    scheduleRuleKind: "WEBINAR_DATE_OFFSET",
    dayOffset: -2,
    clockTimeMyt: "15:00",
    startOffsetMinutes: null,
    sortOrder: 2,
  },
  {
    slotKey: "countdown_1d",
    name: "1-Day Countdown",
    reminderFormat: "IMAGE",
    bodyTemplate: [
      "🚨 1 DAY TO GO 🚨",
      "",
      "We go live TOMORROW @ {{workshopTime}} for Dr. Jasmine's Reversing Diabetes Workshop 🔥",
      "",
      "If you've been struggling with blood sugar levels that keep fluctuating...",
      "If you're worried about needing more medication, more insulin, or future complications...",
      "Then you must attend tomorrow's session.",
      "",
      "We will be breaking down:",
      "✨ Why blood sugar levels can still stay unstable even when you're trying",
      "✨ What may be happening beneath the surface with diabetes",
      "✨ Why some people slowly head toward more medication, more insulin, and more complications",
      "✨ What needs to be addressed if you want a different outcome",
      "",
      "This is not the kind of session you want to \"catch later.\"",
      "Because once you miss the foundation, you'll miss the full picture of what we are trying to show you.",
      "",
      "If you've been worried about your readings...",
      "your medication increasing...",
      "or where your health may be heading in the next few years...",
      "Then make sure you show up live tomorrow.",
      "",
      "Don't come in halfway.",
      "Don't get distracted.",
      "And don't treat this like just another health talk.",
      "",
      "Here's the zoom link",
      ">> {{zoomLink}}",
      "(Feel free to invite your friends & family to join along)",
      "",
      "Be there live",
      "Because the more you understand your condition properly,",
      "the better decisions you can make from here. 💚",
      "",
      "See you tomorrow at {{workshopTime}}!",
    ].join("\n"),
    scheduleRuleKind: "WEBINAR_DATE_OFFSET",
    dayOffset: -1,
    clockTimeMyt: "20:00",
    startOffsetMinutes: null,
    sortOrder: 3,
  },
  {
    slotKey: "starting_soon",
    name: "Starting Soon",
    reminderFormat: "IMAGE",
    bodyTemplate: [
      "🚨🚨 Workshop Starting Today 🚨🚨",
      "",
      "One thing to remember:",
      "Lowering blood sugar is important.",
      "But understanding why it keeps rising in the first place is what matters even more.",
      "That is the part many people never get properly explained.",
      "",
      "And that is also why progress can feel frustrating",
      "because you may be managing the numbers without fully understanding the condition underneath.",
      "",
      "Tonight, we will walk through:",
      "- why diabetes is more than just a sugar problem",
      "- what may be keeping the body stuck",
      "- what people often miss when they focus only on control",
      "- what needs to be addressed for a long term health direction",
      "",
      "This session is meant to help you see your condition more clearly",
      "so you can stop guessing and start making more informed decisions about your health.",
      "",
      "If that is something you've been needing,",
      "be there live tonight.",
      "",
      "🗓️ {{sessionDate}}",
      "🕒 {{sessionTime}}",
      "📍 Online",
      "",
      "Zoom Link: {{zoomLink}}",
      "Zoom ID: {{zoomId}}",
      "Zoom Passcode: {{zoomPasscode}}",
      "",
      "Remember to invite your friends & family along.",
      "See you tonight.",
    ].join("\n"),
    scheduleRuleKind: "WEBINAR_DATE_OFFSET",
    dayOffset: 0,
    clockTimeMyt: "11:00",
    startOffsetMinutes: null,
    sortOrder: 4,
  },
  {
    slotKey: "countdown_1h",
    name: "1-Hour Countdown",
    reminderFormat: "IMAGE",
    bodyTemplate: [
      "🚨🚨 1 hour to LIVE 🚨🚨",
      "",
      "If you've been trying to manage diabetes the usual way",
      "but still feel like you're not seeing the full picture",
      "",
      "Tonight will help connect the dots.",
      "",
      "We'll be sharing:",
      "",
      "why blood sugar is only one part of the story",
      "",
      "what may be getting overlooked beneath the surface",
      "",
      "why managing the numbers is not the same as truly improving the condition",
      "",
      "how to start seeing diabetes from a more complete perspective",
      "",
      "Sometimes one new understanding can change the questions you ask",
      "and that can change the decisions you make after that.",
      "",
      "🕒 {{workshopTime}}",
      "Join us here:",
      "👉 {{zoomLink}}",
      "Zoom ID: {{zoomId}}",
      "Zoom Passcode: {{zoomPasscode}}",
      "",
      "We have more registrants than the room can hold,",
      "so please join a few minutes early to avoid missing out.",
      "",
      "See you there!",
    ].join("\n"),
    scheduleRuleKind: "EVENT_START_OFFSET",
    dayOffset: null,
    clockTimeMyt: null,
    startOffsetMinutes: -60,
    sortOrder: 5,
  },
  {
    slotKey: "live_now",
    name: "LIVE NOW",
    reminderFormat: "TEXT",
    bodyTemplate: [
      "🚨 We are LIVE now!",
      "→ {{zoomLink}}",
      "",
      "Most people with diabetes were taught how to manage the numbers.",
      "Very few were taught how to understand what may actually be driving the condition underneath.",
      "",
      "That is what we are breaking down right now.",
      "Once you see it, your entire perspective can change.",
      "",
      "Join now:",
      "👉 {{zoomLink}}",
    ].join("\n"),
    scheduleRuleKind: "EVENT_START_OFFSET",
    dayOffset: null,
    clockTimeMyt: null,
    startOffsetMinutes: -2,
    sortOrder: 6,
  },
  {
    slotKey: "post_live_sticker",
    name: "Post-Live Sticker",
    reminderFormat: "STICKER",
    bodyTemplate: null,
    scheduleRuleKind: "EVENT_START_OFFSET",
    dayOffset: null,
    clockTimeMyt: null,
    startOffsetMinutes: 18,
    sortOrder: 7,
  },
] as const;

/**
 * Seeds Show Up reminder template slots for a project.
 * Preserves uploaded `mediaUrl` / `stickerUrl`; refreshes SOP caption copy + schedule metadata.
 */
export async function seedReminderTemplatesForProject(
  prisma: PrismaClient,
  projectId: string,
): Promise<void> {
  for (const slot of REMINDER_TEMPLATE_SLOT_DEFINITIONS) {
    const createData: Prisma.ReminderTemplateCreateInput = {
      project: { connect: { id: projectId } },
      slotKey: slot.slotKey,
      name: slot.name,
      reminderFormat: slot.reminderFormat,
      bodyTemplate: slot.bodyTemplate,
      scheduleRuleKind: slot.scheduleRuleKind,
      dayOffset: slot.dayOffset,
      clockTimeMyt: slot.clockTimeMyt,
      startOffsetMinutes: slot.startOffsetMinutes,
      sortOrder: slot.sortOrder,
    };

    await prisma.reminderTemplate.upsert({
      where: {
        projectId_slotKey: { projectId, slotKey: slot.slotKey },
      },
      create: createData,
      update: {
        name: slot.name,
        reminderFormat: slot.reminderFormat,
        bodyTemplate: slot.bodyTemplate,
        scheduleRuleKind: slot.scheduleRuleKind,
        dayOffset: slot.dayOffset,
        clockTimeMyt: slot.clockTimeMyt,
        startOffsetMinutes: slot.startOffsetMinutes,
        sortOrder: slot.sortOrder,
      },
    });
  }
}
